#ifndef __EXTENDEDSCRIPTS_H__
#define __EXTENDEDSCRIPTS_H__

const char *hud_old =
"hudold = [\n"
    "ammobar 0\n"
    "ammobardisableininsta 1\n"
    "ammobardisablewithgui 0\n"
    "ammobarfilterempty 0\n"
    "ammobarhorizontal 0\n"
    "ammobaroffset_start_x -1\n"
    "ammobaroffset_x 10\n"
    "ammobaroffset_y 500\n"
    "ammobarselectedcolor_a 150\n"
    "ammobarselectedcolor_b 255\n"
    "ammobarselectedcolor_g 200\n"
    "ammobarselectedcolor_r 100\n"
    "gameclockcolorbg_a 50\n"
    "gameclockcolorbg_b 255\n"
    "gameclockcolorbg_g 200\n"
    "gameclockcolorbg_r 100\n"
    "ammobarsize 5\n"
    "coloredammo 0\n"
    "coloredhealth 0\n"
    "gameclock 0\n"
    "gameclockcolor_a 255\n"
    "gameclockcolor_b 255\n"
    "gameclockcolor_g 255\n"
    "gameclockcolor_r 255\n"
    "gameclockdisablewithgui 0\n"
    "gameclockoffset_start_x 1\n"
    "gameclockoffset_x 10\n"
    "gameclockoffset_y 300\n"
    "gameclocksize 5\n"
    "hudscores 0\n"
    "hudscoresdisablewithgui 0\n"
    "hudscoresenemycolor_a 255\n"
    "hudscoresenemycolor_b 0\n"
    "hudscoresenemycolor_g 0\n"
    "hudscoresenemycolor_r 255\n"
    "hudscoresenemycolorbg_a 50\n"
    "hudscoresenemycolorbg_b 85\n"
    "hudscoresenemycolorbg_g 85\n"
    "hudscoresenemycolorbg_r 255\n"
    "hudscoresoffset_offset_x 1\n"
    "hudscoresoffset_x 10\n"
    "hudscoresoffset_y 350\n"
    "hudscoresplayercolor_a 255\n"
    "hudscoresplayercolor_b 255\n"
    "hudscoresplayercolor_g 255\n"
    "hudscoresplayercolor_r 0\n"
    "hudscoresplayercolorbg_a 50\n"
    "hudscoresplayercolorbg_b 255\n"
    "hudscoresplayercolorbg_g 255\n"
    "hudscoresplayercolorbg_r 0\n"
    "hudscoressize 5\n"
    "newhud 0\n"
    "newhud_ammodisable 0\n"
    "newhud_ammodisableininsta 0\n"
    "newhud_ammodisablewithgui 0\n"
    "newhud_ammoiconssize 60\n"
    "newhud_ammopos_x 580\n"
    "newhud_ammopos_y 960\n"
    "newhud_ammosize 30\n"
    "newhud_hpdisableininsta 0\n"
    "newhud_hpdisablewithgui 0\n"
    "newhud_hpiconssize 60\n"
    "newhud_hppos_x 420\n"
    "newhud_hppos_y 960\n"
    "newhud_hpssize 30\n"
    "newhud_itemsdisablewithgui 0\n"
    "newhud_itemspos_reverse_x 1\n"
    "newhud_itemspos_x 10\n"
    "newhud_itemspos_y 870\n"
    "newhud_itemssize 14\n"
    "newhud_miniconoffset 0\n"
    "newhud_miniconsize 6\n"
    "newhud_miniconwidth 30\n"
    "newhud_spectatorpos_start_x 0\n"
    "newhud_spectatorpos_x 500\n"
    "newhud_spectatorpos_y 110\n"
    "newhud_spectatorsdisablewithgui 1\n"
    "newhud_spectatorsnocolor 1\n"
    "newhud_spectatorsize 5\n"
"]\n";

const char *hud_old_extended =
"hudoldextended = [\n"
    "ammobar 1\n"
    "ammobardisableininsta 1\n"
    "ammobardisablewithgui 1\n"
    "ammobarfilterempty 1\n"
    "ammobarhorizontal 0\n"
    "ammobaroffset_start_x -1\n"
    "ammobaroffset_x 10\n"
    "ammobaroffset_y 500\n"
    "ammobarselectedcolor_a 150\n"
    "ammobarselectedcolor_b 255\n"
    "ammobarselectedcolor_g 200\n"
    "ammobarselectedcolor_r 100\n"
    "gameclockcolorbg_a 50\n"
    "gameclockcolorbg_b 255\n"
    "gameclockcolorbg_g 200\n"
    "gameclockcolorbg_r 100\n"
    "ammobarsize 5\n"
    "coloredammo 1\n"
    "coloredhealth 1\n"
    "gameclock 1\n"
    "gameclockcolor_a 255\n"
    "gameclockcolor_b 255\n"
    "gameclockcolor_g 255\n"
    "gameclockcolor_r 255\n"
    "gameclockdisablewithgui 1\n"
    "gameclockoffset_start_x 1\n"
    "gameclockoffset_x 10\n"
    "gameclockoffset_y 300\n"
    "gameclocksize 5\n"
    "hudscores 1\n"
    "hudscoresdisablewithgui 1\n"
    "hudscoresenemycolor_a 255\n"
    "hudscoresenemycolor_b 0\n"
    "hudscoresenemycolor_g 0\n"
    "hudscoresenemycolor_r 255\n"
    "hudscoresenemycolorbg_a 50\n"
    "hudscoresenemycolorbg_b 85\n"
    "hudscoresenemycolorbg_g 85\n"
    "hudscoresenemycolorbg_r 255\n"
    "hudscoresoffset_start_x 1\n"
    "hudscoresoffset_x 10\n"
    "hudscoresoffset_y 350\n"
    "hudscoresplayercolor_a 255\n"
    "hudscoresplayercolor_b 255\n"
    "hudscoresplayercolor_g 255\n"
    "hudscoresplayercolor_r 0\n"
    "hudscoresplayercolorbg_a 50\n"
    "hudscoresplayercolorbg_b 255\n"
    "hudscoresplayercolorbg_g 255\n"
    "hudscoresplayercolorbg_r 0\n"
    "hudscoressize 5\n"
    "newhud 0\n"
    "newhud_ammodisable 0\n"
    "newhud_ammodisableininsta 0\n"
    "newhud_ammodisablewithgui 0\n"
    "newhud_ammoiconssize 60\n"
    "newhud_ammopos_x 580\n"
    "newhud_ammopos_y 960\n"
    "newhud_ammosize 30\n"
    "newhud_hpdisableininsta 0\n"
    "newhud_hpdisablewithgui 0\n"
    "newhud_hpiconssize 60\n"
    "newhud_hppos_x 420\n"
    "newhud_hppos_y 960\n"
    "newhud_hpssize 30\n"
    "newhud_itemsdisablewithgui 0\n"
    "newhud_itemspos_reverse_x 1\n"
    "newhud_itemspos_x 10\n"
    "newhud_itemspos_y 870\n"
    "newhud_itemssize 14\n"
    "newhud_miniconoffset 0\n"
    "newhud_miniconsize 6\n"
    "newhud_miniconwidth 30\n"
    "newhud_spectatorpos_start_x 0\n"
    "newhud_spectatorpos_x 500\n"
    "newhud_spectatorpos_y 110\n"
    "newhud_spectatorsdisablewithgui 1\n"
    "newhud_spectatorsnocolor 1\n"
    "newhud_spectatorsize 5\n"
"]\n";

const char *hud_new1 =
"hudnew1 = [\n"
    "ammobar 1\n"
    "ammobardisableininsta 1\n"
    "ammobardisablewithgui 1\n"
    "ammobarfilterempty 1\n"
    "ammobarhorizontal 0\n"
    "ammobaroffset_start_x -1\n"
    "ammobaroffset_x 10\n"
    "ammobaroffset_y 500\n"
    "ammobarselectedcolor_a 150\n"
    "ammobarselectedcolor_b 255\n"
    "ammobarselectedcolor_g 200\n"
    "ammobarselectedcolor_r 100\n"
    "ammobarsize 10\n"
    "coloredammo 1\n"
    "coloredhealth 1\n"
    "gameclock 1\n"
    "gameclockcolor_a 255\n"
    "gameclockcolor_b 255\n"
    "gameclockcolor_g 255\n"
    "gameclockcolor_r 255\n"
    "gameclockcolorbg_a 50\n"
    "gameclockcolorbg_b 255\n"
    "gameclockcolorbg_g 200\n"
    "gameclockcolorbg_r 100\n"
    "gameclockdisablewithgui 0\n"
    "gameclockoffset_start_x -1\n"
    "gameclockoffset_x 780\n"
    "gameclockoffset_y 960\n"
    "gameclocksize 15\n"
    "hudscores 1\n"
    "hudscoresdisablewithgui 1\n"
    "hudscoresenemycolor_a 255\n"
    "hudscoresenemycolor_b 0\n"
    "hudscoresenemycolor_g 0\n"
    "hudscoresenemycolor_r 255\n"
    "hudscoresenemycolorbg_a 50\n"
    "hudscoresenemycolorbg_b 85\n"
    "hudscoresenemycolorbg_g 85\n"
    "hudscoresenemycolorbg_r 255\n"
    "hudscoresoffset_start_x 1\n"
    "hudscoresoffset_x 10\n"
    "hudscoresoffset_y 800\n"
    "hudscoresplayercolor_a 255\n"
    "hudscoresplayercolor_b 255\n"
    "hudscoresplayercolor_g 255\n"
    "hudscoresplayercolor_r 0\n"
    "hudscoresplayercolorbg_a 50\n"
    "hudscoresplayercolorbg_b 255\n"
    "hudscoresplayercolorbg_g 255\n"
    "hudscoresplayercolorbg_r 0\n"
    "hudscoressize 10\n"
    "newhud 1\n"
    "newhud_ammodisable 0\n"
    "newhud_ammodisableininsta 0\n"
    "newhud_ammodisablewithgui 0\n"
    "newhud_ammoiconssize 60\n"
    "newhud_ammopos_x 580\n"
    "newhud_ammopos_y 960\n"
    "newhud_ammosize 30\n"
    "newhud_hpdisableininsta 0\n"
    "newhud_hpdisablewithgui 0\n"
    "newhud_hpiconssize 60\n"
    "newhud_hppos_x 420\n"
    "newhud_hppos_y 960\n"
    "newhud_hpssize 30\n"
    "newhud_itemsdisablewithgui 0\n"
    "newhud_itemspos_reverse_x 1\n"
    "newhud_itemspos_x 10\n"
    "newhud_itemspos_y 870\n"
    "newhud_itemssize 14\n"
    "newhud_miniconoffset 0\n"
    "newhud_miniconsize 6\n"
    "newhud_miniconwidth 30\n"
    "newhud_spectatorpos_start_x 0\n"
    "newhud_spectatorpos_x 500\n"
    "newhud_spectatorpos_y 110\n"
    "newhud_spectatorsdisablewithgui 1\n"
    "newhud_spectatorsnocolor 1\n"
    "newhud_spectatorsize 5\n"
"]\n";

const char *hud_new2 =
"hudnew2 = [\n"
    "ammobar 1\n"
    "ammobardisableininsta 1\n"
    "ammobardisablewithgui 0\n"
    "ammobarfilterempty 1\n"
    "ammobarhorizontal 1\n"
    "ammobaroffset_start_x 0\n"
    "ammobaroffset_x 500\n"
    "ammobaroffset_y 900\n"
    "ammobarselectedcolor_a 150\n"
    "ammobarselectedcolor_b 255\n"
    "ammobarselectedcolor_g 200\n"
    "ammobarselectedcolor_r 100\n"
    "ammobarsize 10\n"
    "coloredammo 1\n"
    "coloredhealth 1\n"
    "gameclock 1\n"
    "gameclockcolor_a 255\n"
    "gameclockcolor_b 255\n"
    "gameclockcolor_g 255\n"
    "gameclockcolor_r 255\n"
    "gameclockcolorbg_a 50\n"
    "gameclockcolorbg_b 255\n"
    "gameclockcolorbg_g 200\n"
    "gameclockcolorbg_r 100\n"
    "gameclockdisablewithgui 0\n"
    "gameclockoffset_start_x 1\n"
    "gameclockoffset_x 620\n"
    "gameclockoffset_y 970\n"
    "gameclocksize 10\n"
    "hudscores 1\n"
    "hudscoresdisablewithgui 0\n"
    "hudscoresenemycolor_a 255\n"
    "hudscoresenemycolor_b 0\n"
    "hudscoresenemycolor_g 0\n"
    "hudscoresenemycolor_r 255\n"
    "hudscoresenemycolorbg_a 50\n"
    "hudscoresenemycolorbg_b 85\n"
    "hudscoresenemycolorbg_g 85\n"
    "hudscoresenemycolorbg_r 255\n"
    "hudscoresoffset_start_x -1\n"
    "hudscoresoffset_x 620\n"
    "hudscoresoffset_y 970\n"
    "hudscoresplayercolor_a 255\n"
    "hudscoresplayercolor_b 255\n"
    "hudscoresplayercolor_g 255\n"
    "hudscoresplayercolor_r 0\n"
    "hudscoresplayercolorbg_a 50\n"
    "hudscoresplayercolorbg_b 255\n"
    "hudscoresplayercolorbg_g 255\n"
    "hudscoresplayercolorbg_r 0\n"
    "hudscoressize 10\n"
    "newhud 1\n"
    "newhud_ammodisable 0\n"
    "newhud_ammodisableininsta -1\n"
    "newhud_ammodisablewithgui 0\n"
    "newhud_ammoiconssize 60\n"
    "newhud_ammopos_x 470\n"
    "newhud_ammopos_y 970\n"
    "newhud_ammosize 30\n"
    "newhud_hpdisableininsta 1\n"
    "newhud_hpdisablewithgui 0\n"
    "newhud_hpiconssize 60\n"
    "newhud_hppos_x 500\n"
    "newhud_hppos_y 970\n"
    "newhud_hpssize 30\n"
    "newhud_itemsdisablewithgui 0\n"
    "newhud_itemspos_reverse_x 1\n"
    "newhud_itemspos_x 10\n"
    "newhud_itemspos_y 870\n"
    "newhud_itemssize 14\n"
    "newhud_miniconoffset 0\n"
    "newhud_miniconsize 6\n"
    "newhud_miniconwidth 28\n"
    "newhud_spectatorpos_start_x 0\n"
    "newhud_spectatorpos_x 500\n"
    "newhud_spectatorpos_y 110\n"
    "newhud_spectatorsdisablewithgui 1\n"
    "newhud_spectatorsnocolor 1\n"
    "newhud_spectatorsize 5\n"
"]\n";


const char *resetlagometer =
"resetlagometer = [\n"
    "lagometer 0\n"
    "lagometercolsz 1\n"
    "lagometerdisablewithgui 1\n"
    "lagometerheight 100\n"
    "lagometerlen 100\n"
    "lagometernobg 0\n"
    "lagometeronlypingself 1\n"
    "lagometerpingsz 150\n"
    "lagometerpos_start_x 1\n"
    "lagometerpos_x 10\n"
    "lagometerpos_y 500\n"
    "lagometershowping 1\n"
"]\n";


const char *extended_settings_gui =
"newgui extended_settings [\n"

    "guicheckbox \"Show servers preview\" showserverpreviews\n"
    "guicheckbox \"Use following player team\" usefollowingplayerteam\n"
    "guicheckbox \"Log players stats on game end\" dumpstatsongameend\n"
    "guistrut 1\n"

    "guicheckbox \"No sparks for hitscan weapons\" reducesparks\n"
    "guicheckbox \"No explosion animation\" reduceexplosions\n"
    "guicheckbox \"No explosion debris\" removeexplosionsdebris\n"
    "guistrut 1\n"

    "guitext \"Smoke density (for rockets and grenades):\" 0\n"
    "guislider smokefps\n"
    "guistrut 1\n"

    "guicheckbox \"Colored health\" coloredhealth\n"
    "guicheckbox \"Colored ammo\" coloredammo\n"
    "guistrut 1\n"

    "guitext \"Position package delay (less values are smoothing network lags):\" 0\n"
    "guislider positionpackagedelay\n"
    "guistrut 1\n"


    "guitab \"Scoreboard\"\n"

    "guicheckbox \"Show flags scored\" showflags\n"
    "guilist [\n"
    "guicheckbox \"Show frags in all modes\" showfrags\n"
    "guibar\n"
    "guicheckbox \"Show net in frags field\" shownetfrags\n"
    "guibar\n"
    "guicheckbox \"Net colors\" netfragscolors\n"
    "]\n"
    "guilist [\n"
    "guicheckbox \"Show damage dealt\" showdamagedealt\n"
    "guibar\n"
    "guicheckbox \"Show net in damage field\" shownetdamage\n"
    "guibar\n"
    "guicheckbox \"Net colors\" netdamagecolors\n"
    "]\n"
    "guicheckbox \"Show accuracy\" showacc\n"


    "guitab \"Lagometer\"\n"

    "guilist [\n"
    "guicheckbox \"Show lagomter\" lagometer\n"
    "guibar\n"
    "guicheckbox \"Disable background\" lagometernobg\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" lagometerdisablewithgui\n"
    "]\n"
    "guilist [\n"
    "guicheckbox \"Show ping in lagomter\" lagometershowping\n"
    "guibar\n"
    "guicheckbox \"Only ping in self lagometer\" lagometeronlypingself\n"
    "]\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y):\" 0\n"
    "guilist [\n"
    "guitext \"X offset start\"\n"
    "guibar\n"
    "guiradio \"Left\" lagometerpos_start_x -1 \"lagometerpos_start_x -1\"\n"
    "guibar\n"
    "guiradio \"Center\" lagometerpos_start_x 0 \"lagometerpos_start_x 0\"\n"
    "guibar\n"
    "guiradio \"Right\" lagometerpos_start_x 1 \"lagometerpos_start_x 1\"\n"
    "]\n"
    "guislider lagometerpos_x\n"
    "guislider lagometerpos_y\n"
    "guistrut 1\n"

    "guitext \"Lagometer number of columns:\" 0\n"
    "guislider lagometerlen\n"
    "guitext \"Lagometer column width:\" 0\n"
    "guislider lagometercolsz\n"
    "guistrut 1\n"

    "guitext \"Lagometer height:\" 0\n"
    "guislider lagometerheight\n"
    "guitext \"Lagometer ping size:\" 0\n"
    "guislider lagometerpingsz\n"
    "guistrut 1\n"


    "guitab \"HUDs\"\n"

    "guititle \"Warning: All current HUD settings will be reset to the selected HUD settings\"\n"
    "guistrut 1\n"
    "guibutton \"Default HUD\" \"hudold\" \n"
    "guistrut 1\n"
    "guibutton \"Default extended HUD\" \"hudoldextended\" \n"
    "guistrut 1\n"
    "guibutton \"New customisable HUD (example1)\" \"hudnew1\"\n"
    "guistrut 1\n"
    "guibutton \"New customisable HUD (example2)\" \"hudnew2\"\n"
    "guistrut 1\n"
    "guibutton \"Reset lagometer settings\" \"resetlagometer\"\n"
    "guistrut 1\n"


    "guitab \"Ammobar\"\n"

    "guilist [\n"
    "guicheckbox \"Show ammobar\" ammobar\n"
    "guibar\n"
    "guicheckbox \"Don't show in insta modes\" ammobardisableininsta\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" ammobardisablewithgui\n"
    "]\n"
    "guicheckbox \"Horizontal ammobar\" ammobarhorizontal\n"
    "guicheckbox \"Transparent empty weapons\" ammobarfilterempty\n"
    "guistrut 1\n"

    "guitext \"Size:\" 0\n"
    "guislider ammobarsize\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y):\" 0\n"
    "guilist [\n"
    "guitext \"X offset start\"\n"
    "guibar\n"
    "guiradio \"Left\" ammobaroffset_start_x -1 \"ammobaroffset_start_x -1\"\n"
    "guibar\n"
    "guiradio \"Center\" ammobaroffset_start_x 0 \"ammobaroffset_start_x 0\"\n"
    "guibar\n"
    "guiradio \"Right\" ammobaroffset_start_x 1 \"ammobaroffset_start_x 1\"\n"
    "]\n"
    "guislider ammobaroffset_x\n"
    "guislider ammobaroffset_y\n"
    "guistrut 1\n"

    "guitext \"Selected gun background (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider ammobarselectedcolor_r\n"
    "guislider ammobarselectedcolor_g\n"
    "guislider ammobarselectedcolor_b\n"
    "guislider ammobarselectedcolor_a\n"


    "guitab \"Clock\"\n"

    "guilist [\n"
    "guicheckbox \"Show clock\" gameclock\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" gameclockdisablewithgui\n"
    "]\n"
    "guitext \"Size:\" 0\n"
    "guislider gameclocksize\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y)^f~:\" 0\n"
    "guilist [\n"
    "guitext \"X offset start\"\n"
    "guibar\n"
    "guiradio \"Left\" gameclockoffset_start_x -1 \"gameclockoffset_start_x -1\"\n"
    "guibar\n"
    "guiradio \"Center\" gameclockoffset_start_x 0 \"gameclockoffset_start_x 0\"\n"
    "guibar\n"
    "guiradio \"Right\" gameclockoffset_start_x 1 \"gameclockoffset_start_x 1\"\n"
    "]\n"
    "guislider gameclockoffset_x\n"
    "guislider gameclockoffset_y\n"


    "guitab \"#2\"\n"

    "guitext \"Clock text color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider gameclockcolor_r\n"
    "guislider gameclockcolor_g\n"
    "guislider gameclockcolor_b\n"
    "guislider gameclockcolor_a\n"
    "guistrut 1\n"

    "guitext \"Clock background color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider gameclockcolorbg_r\n"
    "guislider gameclockcolorbg_g\n"
    "guislider gameclockcolorbg_b\n"
    "guislider gameclockcolorbg_a\n"


    "guitab \"Scores\"\n"

    "guilist [\n"
    "guicheckbox \"Show hud scores\" hudscores\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" hudscoresdisablewithgui\n"
    "]\n"

    "guitext \"Size:\" 0\n"
    "guislider hudscoressize\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y)^f~:\" 0\n"
    "guilist [\n"
    "guitext \"X offset start\"\n"
    "guibar\n"
    "guiradio \"Left\" hudscoresoffset_start_x -1 \"hudscoresoffset_start_x -1\"\n"
    "guibar\n"
    "guiradio \"Center\" hudscoresoffset_start_x 0 \"hudscoresoffset_start_x 0\"\n"
    "guibar\n"
    "guiradio \"Right\" hudscoresoffset_start_x 1 \"hudscoresoffset_start_x 1\"\n"
    "]\n"
    "guislider hudscoresoffset_x\n"
    "guislider hudscoresoffset_y\n"
    "guistrut 1\n"

    "guitext \"Player score text color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider hudscoresplayercolor_r\n"
    "guislider hudscoresplayercolor_g\n"
    "guislider hudscoresplayercolor_b\n"
    "guislider hudscoresplayercolor_a\n"


    "guitab \"#2\"\n"

    "guitext \"Player score background color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider hudscoresplayercolorbg_r\n"
    "guislider hudscoresplayercolorbg_g\n"
    "guislider hudscoresplayercolorbg_b\n"
    "guislider hudscoresplayercolorbg_a\n"
    "guistrut 1\n"

    "guitext \"Enemy score text color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider hudscoresenemycolor_r\n"
    "guislider hudscoresenemycolor_g\n"
    "guislider hudscoresenemycolor_b\n"
    "guislider hudscoresenemycolor_a\n"
    "guistrut 1\n"

    "guitext \"Enemy score background color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider hudscoresenemycolorbg_r\n"
    "guislider hudscoresenemycolorbg_g\n"
    "guislider hudscoresenemycolorbg_b\n"
    "guislider hudscoresenemycolorbg_a\n"


    "guitab \"NewHUD\"\n"

    "guititle \"Warning: Settings have effect only when new HUD is enabled\"\n"
    "guicheckbox \"Enable new HUD\" newhud\n"
    "guistrut 1\n"

    "guititle \"New HUD HP/Armour settings\"\n"
    "guilist [\n"
    "guicheckbox \"Don't show in insta modes\" newhud_hpdisableininsta\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" newhud_hpdisablewithgui\n"
    "]\n"

    "guitext \"Size:\" 0\n"
    "guislider newhud_hpssize\n"
    "guitext \"Icon size:\" 0\n"
    "guislider newhud_hpiconssize\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y):\" 0\n"
    "guislider newhud_hppos_x\n"
    "guislider newhud_hppos_y\n"


    "guitab \"#2\"\n"

    "guititle \"Warning: Settings have effect only when new HUD is enabled\"\n"
    "guicheckbox \"Enable new HUD\" newhud\n"
    "guistrut 1\n"
    
    "guititle \"New HUD Ammo settings\"\n"
    "guilist [\n"
    "guicheckbox \"Don't show ammo\" newhud_ammodisable\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" newhud_ammodisablewithgui\n"
    "]\n"
    "guilist [\n"
    "guitext \"Insta modes behaviour\"\n"
    "guibar\n"
    "guiradio \"Show in all modes\" newhud_ammodisableininsta 0 \"newhud_ammodisableininsta 0\"\n"
    "guibar\n"
    "guiradio \"Show in non-insta modes\" newhud_ammodisableininsta -1 \"newhud_ammodisableininsta -1\"\n"
    "guibar\n"
    "guiradio \"Show only in insta modes\" newhud_ammodisableininsta 1 \"newhud_ammodisableininsta 1\"\n"
    "]\n"
    "guitext \"Size:\" 0\n"
    "guislider newhud_ammosize\n"
    "guitext \"Icon size:\" 0\n"
    "guislider newhud_ammoiconssize\n"
    "guistrut 1\n"

    "guitext \"Ammo offset (X/Y):\" 0\n"
    "guislider newhud_ammopos_x\n"
    "guislider newhud_ammopos_y\n"


    "guitab \"#3\"\n"

    "guititle \"Warning: Settings have effect only when new HUD is enabled\"\n"
    "guicheckbox \"Enable new HUD\" newhud\n"
    "guistrut 1\n"
    
    "guititle \"New HUD spectator settings\"\n"
    "guicheckbox \"Disable with GUI\" newhud_spectatorsdisablewithgui\n"
    "guicheckbox \"No privilege colors\" newhud_spectatorsnocolor\n"
    "guitext \"Size:\" 0\n"
    "guislider newhud_spectatorsize\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y):\" 0\n"
    "guilist [\n"
    "guitext \"X offset start\"\n"
    "guibar\n"
    "guiradio \"Left\" newhud_spectatorpos_start_x -1 \"newhud_spectatorpos_start_x -1\"\n"
    "guibar\n"
    "guiradio \"Center\" newhud_spectatorpos_start_x 0 \"newhud_spectatorpos_start_x 0\"\n"
    "guibar\n"
    "guiradio \"Right\" newhud_spectatorpos_start_x 1 \"newhud_spectatorpos_start_x 1\"\n"
    "]\n"
    "guislider newhud_spectatorpos_x\n"
    "guislider newhud_spectatorpos_y\n"


    "guitab \"#4\"\n"

    "guititle \"Warning: Settings have effect only when new HUD is enabled\"\n"
    "guicheckbox \"Enable new HUD\" newhud\n"
    "guistrut 1\n"
    
    "guititle \"New HUD items settings\"\n"
    "guicheckbox \"Disable with GUI\" newhud_itemsdisablewithgui\n"
    "guitext \"Size:\" 0\n"
    "guislider newhud_itemssize\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y):\" 0\n"
    "guicheckbox \"Use reverse X offset\" newhud_itemspos_reverse_x\n"
    "guislider newhud_itemspos_x\n"
    "guislider newhud_itemspos_y\n"

    
    "guitab \"#5\"\n"

    "guititle \"Warning: Settings have effect only when new HUD is enabled\"\n"
    "guicheckbox \"Enable new HUD\" newhud\n"
    "guistrut 1\n"
    
    "guititle \"New HUD chat settings\"\n"
    "guitext \"Chat Y offset:\" 0\n"
    "guislider newhud_miniconoffset\n"
    "guitext \"Chat lines:\" 0\n"
    "guislider newhud_miniconsize\n"
    "guitext \"Chat width:\" 0\n"
    "guislider newhud_miniconwidth\n"

"] \"Settings\" \n";

const char *game_scripts[] = { extended_settings_gui,
                               hud_old,
                               hud_old_extended,
                               hud_new1,
                               hud_new2,
                               resetlagometer,
                               0 };


#endif
