#ifndef __EXTENDEDSCRIPTS_H__
#define __EXTENDEDSCRIPTS_H__

const char *hud_old =
"hudold = [\n"
    "ammobar 0\n"
    "ammobardisableininsta 1\n"
    "ammobardisablewithgui 0\n"
    "ammobarfilterempty 0\n"
    "ammobarhorizontal 0\n"
    "ammobariconspos -1\n"
    "ammobaroffset_start_x -1\n"
    "ammobaroffset_x 7\n"
    "ammobaroffset_y 500\n"
    "ammobarselectedcolor_a 150\n"
    "ammobarselectedcolor_b 255\n"
    "ammobarselectedcolor_g 200\n"
    "ammobarselectedcolor_r 100\n"
    "gameclockcolorbg_a 50\n"
    "gameclockcolorbg_b 255\n"
    "gameclockcolorbg_g 200\n"
    "gameclockcolorbg_r 100\n"
    "ammobarsize 5\n"
    "coloredammo 0\n"
    "coloredhealth 0\n"
    "gameclock 0\n"
    "gameclockcolor_a 255\n"
    "gameclockcolor_b 255\n"
    "gameclockcolor_g 255\n"
    "gameclockcolor_r 255\n"
    "gameclockdisablewithgui 0\n"
    "gameclockoffset_start_x 1\n"
    "gameclockoffset_x 10\n"
    "gameclockoffset_y 300\n"
    "gameclocksize 5\n"
    "hudscores 0\n"
    "hudscoresdisablewithgui 0\n"
    "hudscoresenemycolor_a 255\n"
    "hudscoresenemycolor_b 0\n"
    "hudscoresenemycolor_g 0\n"
    "hudscoresenemycolor_r 255\n"
    "hudscoresenemycolorbg_a 50\n"
    "hudscoresenemycolorbg_b 85\n"
    "hudscoresenemycolorbg_g 85\n"
    "hudscoresenemycolorbg_r 255\n"
    "hudscoresoffset_start_x 1\n"
    "hudscoresoffset_x 10\n"
    "hudscoresoffset_y 350\n"
    "hudscoresplayercolor_a 255\n"
    "hudscoresplayercolor_b 255\n"
    "hudscoresplayercolor_g 255\n"
    "hudscoresplayercolor_r 0\n"
    "hudscoresplayercolorbg_a 50\n"
    "hudscoresplayercolorbg_b 255\n"
    "hudscoresplayercolorbg_g 255\n"
    "hudscoresplayercolorbg_r 0\n"
    "hudscoressize 5\n"
    "hudscoresvertical 0\n"
    "lagometer 0\n"
    "lagometercolsz 1\n"
    "lagometerdisablewithgui 1\n"
    "lagometerdisablelocal 1\n"
    "lagometerheight 100\n"
    "lagometerlen 100\n"
    "lagometernobg 0\n"
    "lagometeronlypingself 1\n"
    "lagometerpingsz 150\n"
    "lagometerpos_start_x 1\n"
    "lagometerpos_x 10\n"
    "lagometerpos_y 500\n"
    "lagometershowping 1\n"
    "newhud 0\n"
    "newhud_abovehud 925\n"
    "newhud_ammodisable 0\n"
    "newhud_ammodisableininsta 0\n"
    "newhud_ammodisablewithgui 0\n"
    "newhud_ammogap 100\n"
    "newhud_ammoiconssize 60\n"
    "newhud_ammopos_x 580\n"
    "newhud_ammopos_y 960\n"
    "newhud_ammosize 30\n"
    "newhud_hpdisableininsta 0\n"
    "newhud_hpdisablewithgui 0\n"
    "newhud_hpgap 100\n"
    "newhud_hpiconssize 60\n"
    "newhud_hppos_x 420\n"
    "newhud_hppos_y 960\n"
    "newhud_hpssize 30\n"
    "newhud_itemsdisablewithgui 0\n"
    "newhud_itemspos_centerfirst 0\n"
    "newhud_itemspos_reverse_x 1\n"
    "newhud_itemspos_x 10\n"
    "newhud_itemspos_y 870\n"
    "newhud_itemssize 14\n"
    "newhud_miniconoffset 0\n"
    "newhud_miniconsize 6\n"
    "newhud_miniconwidth 30\n"
    "newhud_spectatorpos_start_x 0\n"
    "newhud_spectatorpos_x 500\n"
    "newhud_spectatorpos_y 110\n"
    "newhud_spectatorsdisablewithgui 1\n"
    "newhud_spectatorsnocolor 1\n"
    "newhud_spectatorsize 5\n"
    "newhud_sysoutgamehudlast 0\n"
    "newhud_sysoutoffset 0\n"
"]\n";

const char *hud_old_extended =
"hudoldextended = [\n"
    "ammobar 1\n"
    "ammobardisableininsta 1\n"
    "ammobardisablewithgui 1\n"
    "ammobarfilterempty 1\n"
    "ammobarhorizontal 0\n"
    "ammobariconspos -1\n"
    "ammobaroffset_start_x -1\n"
    "ammobaroffset_x 7\n"
    "ammobaroffset_y 500\n"
    "ammobarselectedcolor_a 150\n"
    "ammobarselectedcolor_b 255\n"
    "ammobarselectedcolor_g 200\n"
    "ammobarselectedcolor_r 100\n"
    "gameclockcolorbg_a 50\n"
    "gameclockcolorbg_b 255\n"
    "gameclockcolorbg_g 200\n"
    "gameclockcolorbg_r 100\n"
    "ammobarsize 5\n"
    "coloredammo 1\n"
    "coloredhealth 1\n"
    "gameclock 1\n"
    "gameclockcolor_a 255\n"
    "gameclockcolor_b 255\n"
    "gameclockcolor_g 255\n"
    "gameclockcolor_r 255\n"
    "gameclockdisablewithgui 1\n"
    "gameclockoffset_start_x 1\n"
    "gameclockoffset_x 10\n"
    "gameclockoffset_y 300\n"
    "gameclocksize 5\n"
    "hudscores 1\n"
    "hudscoresdisablewithgui 1\n"
    "hudscoresenemycolor_a 255\n"
    "hudscoresenemycolor_b 0\n"
    "hudscoresenemycolor_g 0\n"
    "hudscoresenemycolor_r 255\n"
    "hudscoresenemycolorbg_a 50\n"
    "hudscoresenemycolorbg_b 85\n"
    "hudscoresenemycolorbg_g 85\n"
    "hudscoresenemycolorbg_r 255\n"
    "hudscoresoffset_start_x 1\n"
    "hudscoresoffset_x 10\n"
    "hudscoresoffset_y 350\n"
    "hudscoresplayercolor_a 255\n"
    "hudscoresplayercolor_b 255\n"
    "hudscoresplayercolor_g 255\n"
    "hudscoresplayercolor_r 0\n"
    "hudscoresplayercolorbg_a 50\n"
    "hudscoresplayercolorbg_b 255\n"
    "hudscoresplayercolorbg_g 255\n"
    "hudscoresplayercolorbg_r 0\n"
    "hudscoressize 5\n"
    "hudscoresvertical 0\n"
    "lagometer 1\n"
    "lagometercolsz 1\n"
    "lagometerdisablewithgui 1\n"
    "lagometerdisablelocal 1\n"
    "lagometerheight 100\n"
    "lagometerlen 100\n"
    "lagometernobg 0\n"
    "lagometeronlypingself 1\n"
    "lagometerpingsz 150\n"
    "lagometerpos_start_x 1\n"
    "lagometerpos_x 10\n"
    "lagometerpos_y 500\n"
    "lagometershowping 1\n"
    "newhud 0\n"
    "newhud_abovehud 925\n"
    "newhud_ammodisable 0\n"
    "newhud_ammodisableininsta 0\n"
    "newhud_ammodisablewithgui 0\n"
    "newhud_ammogap 100\n"
    "newhud_ammoiconssize 60\n"
    "newhud_ammopos_x 580\n"
    "newhud_ammopos_y 960\n"
    "newhud_ammosize 30\n"
    "newhud_hpdisableininsta 0\n"
    "newhud_hpdisablewithgui 0\n"
    "newhud_hpgap 100\n"
    "newhud_hpiconssize 60\n"
    "newhud_hppos_x 420\n"
    "newhud_hppos_y 960\n"
    "newhud_hpssize 30\n"
    "newhud_itemsdisablewithgui 0\n"
    "newhud_itemspos_centerfirst 0\n"
    "newhud_itemspos_reverse_x 1\n"
    "newhud_itemspos_x 10\n"
    "newhud_itemspos_y 870\n"
    "newhud_itemssize 14\n"
    "newhud_miniconoffset 0\n"
    "newhud_miniconsize 6\n"
    "newhud_miniconwidth 30\n"
    "newhud_spectatorpos_start_x 0\n"
    "newhud_spectatorpos_x 500\n"
    "newhud_spectatorpos_y 110\n"
    "newhud_spectatorsdisablewithgui 1\n"
    "newhud_spectatorsnocolor 1\n"
    "newhud_spectatorsize 5\n"
    "newhud_sysoutgamehudlast 0\n"
    "newhud_sysoutoffset 0\n"
"]\n";

const char *hud_new1 =
"hudnew1 = [\n"
    "ammobar 1\n"
    "ammobardisableininsta 1\n"
    "ammobardisablewithgui 1\n"
    "ammobarfilterempty 1\n"
    "ammobarhorizontal 0\n"
    "ammobariconspos -1\n"
    "ammobaroffset_start_x -1\n"
    "ammobaroffset_x 5\n"
    "ammobaroffset_y 500\n"
    "ammobarselectedcolor_a 150\n"
    "ammobarselectedcolor_b 255\n"
    "ammobarselectedcolor_g 200\n"
    "ammobarselectedcolor_r 100\n"
    "ammobarsize 10\n"
    "coloredammo 1\n"
    "coloredhealth 1\n"
    "gameclock 1\n"
    "gameclockcolor_a 255\n"
    "gameclockcolor_b 255\n"
    "gameclockcolor_g 255\n"
    "gameclockcolor_r 255\n"
    "gameclockcolorbg_a 50\n"
    "gameclockcolorbg_b 255\n"
    "gameclockcolorbg_g 200\n"
    "gameclockcolorbg_r 100\n"
    "gameclockdisablewithgui 0\n"
    "gameclockoffset_start_x -1\n"
    "gameclockoffset_x 780\n"
    "gameclockoffset_y 960\n"
    "gameclocksize 15\n"
    "hudscores 1\n"
    "hudscoresdisablewithgui 1\n"
    "hudscoresenemycolor_a 255\n"
    "hudscoresenemycolor_b 0\n"
    "hudscoresenemycolor_g 0\n"
    "hudscoresenemycolor_r 255\n"
    "hudscoresenemycolorbg_a 50\n"
    "hudscoresenemycolorbg_b 85\n"
    "hudscoresenemycolorbg_g 85\n"
    "hudscoresenemycolorbg_r 255\n"
    "hudscoresoffset_start_x 1\n"
    "hudscoresoffset_x 5\n"
    "hudscoresoffset_y 750\n"
    "hudscoresplayercolor_a 255\n"
    "hudscoresplayercolor_b 255\n"
    "hudscoresplayercolor_g 255\n"
    "hudscoresplayercolor_r 0\n"
    "hudscoresplayercolorbg_a 50\n"
    "hudscoresplayercolorbg_b 255\n"
    "hudscoresplayercolorbg_g 255\n"
    "hudscoresplayercolorbg_r 0\n"
    "hudscoressize 10\n"
    "hudscoresvertical 1\n"
    "lagometer 1\n"
    "lagometercolsz 1\n"
    "lagometerdisablewithgui 1\n"
    "lagometerdisablelocal 1\n"
    "lagometerheight 100\n"
    "lagometerlen 100\n"
    "lagometernobg 0\n"
    "lagometeronlypingself 1\n"
    "lagometerpingsz 150\n"
    "lagometerpos_start_x 1\n"
    "lagometerpos_x 5\n"
    "lagometerpos_y 500\n"
    "lagometershowping 1\n"
    "newhud 1\n"
    "newhud_abovehud 925\n"
    "newhud_ammodisable 0\n"
    "newhud_ammodisableininsta 0\n"
    "newhud_ammodisablewithgui 0\n"
    "newhud_ammogap 100\n"
    "newhud_ammoiconssize 60\n"
    "newhud_ammopos_x 580\n"
    "newhud_ammopos_y 960\n"
    "newhud_ammosize 30\n"
    "newhud_hpdisableininsta 1\n"
    "newhud_hpdisablewithgui 0\n"
    "newhud_hpgap 100\n"
    "newhud_hpiconssize 60\n"
    "newhud_hppos_x 420\n"
    "newhud_hppos_y 960\n"
    "newhud_hpssize 30\n"
    "newhud_itemsdisablewithgui 1\n"
    "newhud_itemspos_centerfirst 0\n"
    "newhud_itemspos_reverse_x 1\n"
    "newhud_itemspos_x 5\n"
    "newhud_itemspos_y 870\n"
    "newhud_itemssize 25\n"
    "newhud_miniconoffset 0\n"
    "newhud_miniconsize 6\n"
    "newhud_miniconwidth 30\n"
    "newhud_spectatorpos_start_x 0\n"
    "newhud_spectatorpos_x 500\n"
    "newhud_spectatorpos_y 110\n"
    "newhud_spectatorsdisablewithgui 1\n"
    "newhud_spectatorsnocolor 1\n"
    "newhud_spectatorsize 5\n"
    "newhud_sysoutgamehudlast 1\n"
    "newhud_sysoutoffset 0\n"
"]\n";

const char *hud_new2 =
"hudnew2 = [\n"
    "ammobar 1\n"
    "ammobardisableininsta 1\n"
    "ammobardisablewithgui 1\n"
    "ammobarfilterempty 1\n"
    "ammobarhorizontal 1\n"
    "ammobariconspos -1\n"
    "ammobaroffset_start_x 0\n"
    "ammobaroffset_x 500\n"
    "ammobaroffset_y 900\n"
    "ammobarselectedcolor_a 150\n"
    "ammobarselectedcolor_b 255\n"
    "ammobarselectedcolor_g 200\n"
    "ammobarselectedcolor_r 100\n"
    "ammobarsize 10\n"
    "coloredammo 1\n"
    "coloredhealth 1\n"
    "gameclock 1\n"
    "gameclockcolor_a 255\n"
    "gameclockcolor_b 255\n"
    "gameclockcolor_g 255\n"
    "gameclockcolor_r 255\n"
    "gameclockcolorbg_a 50\n"
    "gameclockcolorbg_b 255\n"
    "gameclockcolorbg_g 200\n"
    "gameclockcolorbg_r 100\n"
    "gameclockdisablewithgui 0\n"
    "gameclockoffset_start_x 1\n"
    "gameclockoffset_x 620\n"
    "gameclockoffset_y 965\n"
    "gameclocksize 10\n"
    "hudscores 1\n"
    "hudscoresdisablewithgui 0\n"
    "hudscoresenemycolor_a 255\n"
    "hudscoresenemycolor_b 0\n"
    "hudscoresenemycolor_g 0\n"
    "hudscoresenemycolor_r 255\n"
    "hudscoresenemycolorbg_a 50\n"
    "hudscoresenemycolorbg_b 85\n"
    "hudscoresenemycolorbg_g 85\n"
    "hudscoresenemycolorbg_r 255\n"
    "hudscoresoffset_start_x -1\n"
    "hudscoresoffset_x 620\n"
    "hudscoresoffset_y 965\n"
    "hudscoresplayercolor_a 255\n"
    "hudscoresplayercolor_b 255\n"
    "hudscoresplayercolor_g 255\n"
    "hudscoresplayercolor_r 0\n"
    "hudscoresplayercolorbg_a 50\n"
    "hudscoresplayercolorbg_b 255\n"
    "hudscoresplayercolorbg_g 255\n"
    "hudscoresplayercolorbg_r 0\n"
    "hudscoressize 10\n"
    "hudscoresvertical 0\n"
    "lagometer 1\n"
    "lagometercolsz 1\n"
    "lagometerdisablewithgui 1\n"
    "lagometerdisablelocal 1\n"
    "lagometerheight 100\n"
    "lagometerlen 100\n"
    "lagometernobg 0\n"
    "lagometeronlypingself 1\n"
    "lagometerpingsz 150\n"
    "lagometerpos_start_x 1\n"
    "lagometerpos_x 5\n"
    "lagometerpos_y 500\n"
    "lagometershowping 1\n"
    "newhud 1\n"
    "newhud_abovehud 925\n"
    "newhud_ammodisable 0\n"
    "newhud_ammodisableininsta -1\n"
    "newhud_ammodisablewithgui 0\n"
    "newhud_ammogap 100\n"
    "newhud_ammoiconssize 60\n"
    "newhud_ammopos_x 500\n"
    "newhud_ammopos_y 965\n"
    "newhud_ammosize 30\n"
    "newhud_hpdisableininsta 1\n"
    "newhud_hpdisablewithgui 0\n"
    "newhud_hpgap 100\n"
    "newhud_hpiconssize 60\n"
    "newhud_hppos_x 500\n"
    "newhud_hppos_y 965\n"
    "newhud_hpssize 30\n"
    "newhud_itemsdisablewithgui 1\n"
    "newhud_itemspos_centerfirst 0\n"
    "newhud_itemspos_reverse_x 1\n"
    "newhud_itemspos_x 5\n"
    "newhud_itemspos_y 870\n"
    "newhud_itemssize 14\n"
    "newhud_miniconoffset 0\n"
    "newhud_miniconsize 6\n"
    "newhud_miniconwidth 28\n"
    "newhud_spectatorpos_start_x 0\n"
    "newhud_spectatorpos_x 500\n"
    "newhud_spectatorpos_y 110\n"
    "newhud_spectatorsdisablewithgui 1\n"
    "newhud_spectatorsnocolor 1\n"
    "newhud_spectatorsize 5\n"
    "newhud_sysoutgamehudlast 1\n"
    "newhud_sysoutoffset 0\n"
"]\n";

const char *hud_new3 =
"hudnew3 = [\n"
    "ammobar 1\n"
    "ammobardisableininsta 1\n"
    "ammobardisablewithgui 0\n"
    "ammobarfilterempty 1\n"
    "ammobarhorizontal 1\n"
    "ammobariconspos 0\n"
    "ammobaroffset_start_x 0\n"
    "ammobaroffset_x 675\n"
    "ammobaroffset_y 950\n"
    "ammobarselectedcolor_a 150\n"
    "ammobarselectedcolor_b 255\n"
    "ammobarselectedcolor_g 200\n"
    "ammobarselectedcolor_r 100\n"
    "ammobarsize 10\n"
    "coloredammo 1\n"
    "coloredhealth 1\n"
    "gameclock 1\n"
    "gameclockcolor_a 255\n"
    "gameclockcolor_b 255\n"
    "gameclockcolor_g 255\n"
    "gameclockcolor_r 255\n"
    "gameclockcolorbg_a 50\n"
    "gameclockcolorbg_b 255\n"
    "gameclockcolorbg_g 200\n"
    "gameclockcolorbg_r 100\n"
    "gameclockdisablewithgui 0\n"
    "gameclockoffset_start_x 1\n"
    "gameclockoffset_x 5\n"
    "gameclockoffset_y 950\n"
    "gameclocksize 15\n"
    "hudscores 1\n"
    "hudscoresdisablewithgui 0\n"
    "hudscoresenemycolor_a 255\n"
    "hudscoresenemycolor_b 0\n"
    "hudscoresenemycolor_g 0\n"
    "hudscoresenemycolor_r 255\n"
    "hudscoresenemycolorbg_a 50\n"
    "hudscoresenemycolorbg_b 85\n"
    "hudscoresenemycolorbg_g 85\n"
    "hudscoresenemycolorbg_r 255\n"
    "hudscoresoffset_start_x -1\n"
    "hudscoresoffset_x 5\n"
    "hudscoresoffset_y 950\n"
    "hudscoresplayercolor_a 255\n"
    "hudscoresplayercolor_b 255\n"
    "hudscoresplayercolor_g 255\n"
    "hudscoresplayercolor_r 0\n"
    "hudscoresplayercolorbg_a 50\n"
    "hudscoresplayercolorbg_b 255\n"
    "hudscoresplayercolorbg_g 255\n"
    "hudscoresplayercolorbg_r 0\n"
    "hudscoressize 15\n"
    "hudscoresvertical 0\n"
    "lagometer 1\n"
    "lagometercolsz 1\n"
    "lagometerdisablelocal 1\n"
    "lagometerdisablewithgui 1\n"
    "lagometerheight 100\n"
    "lagometerlen 100\n"
    "lagometernobg 0\n"
    "lagometeronlypingself 1\n"
    "lagometerpingsz 150\n"
    "lagometerpos_start_x 1\n"
    "lagometerpos_x 5\n"
    "lagometerpos_y 500\n"
    "lagometershowping 1\n"
    "newhud 1\n"
    "newhud_abovehud 900\n"
    "newhud_ammodisable 0\n"
    "newhud_ammodisableininsta -1\n"
    "newhud_ammodisablewithgui 0\n"
    "newhud_ammogap 100\n"
    "newhud_ammoiconssize 60\n"
    "newhud_ammopos_x 500\n"
    "newhud_ammopos_y 950\n"
    "newhud_ammosize 30\n"
    "newhud_hpdisableininsta 1\n"
    "newhud_hpdisablewithgui 0\n"
    "newhud_hpgap 100\n"
    "newhud_hpiconssize 60\n"
    "newhud_hppos_x 325\n"
    "newhud_hppos_y 950\n"
    "newhud_hpssize 45\n"
    "newhud_itemsdisablewithgui 1\n"
    "newhud_itemspos_centerfirst 1\n"
    "newhud_itemspos_reverse_x 0\n"
    "newhud_itemspos_x 500\n"
    "newhud_itemspos_y 830\n"
    "newhud_itemssize 26\n"
    "newhud_miniconoffset 100\n"
    "newhud_miniconsize 5\n"
    "newhud_miniconwidth 40\n"
    "newhud_spectatorpos_start_x 0\n"
    "newhud_spectatorpos_x 500\n"
    "newhud_spectatorpos_y 110\n"
    "newhud_spectatorsdisablewithgui 1\n"
    "newhud_spectatorsize 5\n"
    "newhud_spectatorsnocolor 1\n"
    "newhud_sysoutgamehudlast 1\n"
    "newhud_sysoutoffset 100\n"
"]\n";


const char *extended_settings_gui =
"newgui extended_settings [\n"
    "local oldstatkeys newstatkeys kk\n"
    "oldstatkeys = (searchbinds showplayerstats)\n"
    "newstatkeys = (searchbinds showplayerstats)\n"
    "guilist [\n"
    "guitext \"Show player stats bind: \"\n"
    "guikeyfield newstatkeys 20 [looplist kk [@@oldstatkeys] [bind $kk]; looplist kk $newstatkeys [bind $kk showplayerstats]]\n"
    "]\n"
    "guistrut 1\n"
    "guilist [\n"
    "guicheckbox \"Autodownload server demos\" autodownloaddemos\n"
    "guibar\n"
    "guicheckbox \"Only ended games\" autodownloadonlyended\n"
    "]\n"
    "guistrut 1\n"
    "guicheckbox \"Frag beep\" fragbeep\n"
    "guistrut 1\n"
    "guicheckbox \"Log players stats when game ends\" dumpstatsongameend\n"
    "guistrut 1\n"

    "guitab \"Spectating\"\n"
    "guilist [\n"
    "guitext \"Auto follow when fragged\"\n"
    "guibar\n"
    "guiradio \"Off\" autofollowchangewhenkilled 0 \"autofollowchangewhenkilled 0\"\n"
    "guibar\n"
    "guiradio \"Killer\" autofollowchangewhenkilled 1 \"autofollowchangewhenkilled 1\"\n"
    "guibar\n"
    "guiradio \"MaxHP\" autofollowchangewhenkilled 2 \"autofollowchangewhenkilled 2\"\n"
    "]\n"
    "guistrut 1\n"
    "guicheckbox \"Use following player team\" usefollowingplayerteam\n"
    "guistrut 1\n"
    "guicheckbox \"Auto follow only current team\" autofollowonlysameteam\n"
    "guistrut 1\n"
    "guicheckbox \"Auto follow flag carrier\" autofollowflagcarrier\n"
    "guistrut 1\n"

    "guitab \"Scoreboard\"\n"

    "guicheckbox \"Show flags scored\" showflags\n"
    "guistrut 1\n"
    "guilist [\n"
    "guicheckbox \"Show frags in all modes\" showfrags\n"
    "guibar\n"
    "guicheckbox \"Show net in frags field\" shownetfrags\n"
    "guibar\n"
    "guicheckbox \"Net colors\" netfragscolors\n"
    "]\n"
    "guistrut 1\n"
    "guilist [\n"
    "guicheckbox \"Show damage dealt\" showdamagedealt\n"
    "guibar\n"
    "guicheckbox \"Show net in damage field\" shownetdamage\n"
    "guibar\n"
    "guicheckbox \"Net colors\" netdamagecolors\n"
    "]\n"
    "guistrut 1\n"
    "guilist [\n"
    "guicheckbox \"Show accuracy\" showacc\n"
    "guibar\n"
    "guicheckbox \"Use accuracy from server\" showserveracc\n"
    "]\n"
    "guistrut 1\n"
    "guicheckbox \"Show compact spectators list\" showshortspecslist\n"

    "guitab \"Particles\"\n"

    "guilist [\n"
    "guicheckbox \"No sparks for hitscan weapons\" reducesparks\n"
    "guibar\n"
    "guicheckbox \"No explosion animation\" reduceexplosions\n"
    "guibar\n"
    "guicheckbox \"No explosion debris\" removeexplosionsdebris\n"
    "]\n"
    "guistrut 1\n"

    "guitext \"Smoke density (for rockets and grenades):\" 0\n"
    "guislider smokefps\n"
    "guistrut 1\n"

    "guitext \"Rifle trail time:\" 0\n"
    "guislider rifletrailtime\n"
    "guistrut 1\n"

    "guitext \"Rifle trail size:\" 0\n"
    "guislider rifletrailsize\n"
    "guistrut 1\n"

    "guitext \"Rifle trail gravity:\" 0\n"
    "guislider rifletrailgravity\n"

    "guitab \"\"\n"

    "guitext \"Rifle trail color (^f3R^f~/^f0G^f~/^f1B^f~):\" 0\n"
    "guislider rifletrailcolor_r\n"
    "guislider rifletrailcolor_g\n"
    "guislider rifletrailcolor_b\n"
    "guistrut 1\n"

    "guitext \"Damage numbers color (^f3R^f~/^f0G^f~/^f1B^f~):\" 0\n"
    "guislider damagecolor_r\n"
    "guislider damagecolor_g\n"
    "guislider damagecolor_b\n"

    "guitab \"Colors\"\n"

    "guitext \"Player team text color:\" 0\n"
    "guilist [\n"
    "guiradio \"Green\" playerteamcolor 0 \"playerteamcolor 0\"\n"
    "guibar\n"
    "guiradio \"Blue\" playerteamcolor 1 \"playerteamcolor 1\"\n"
    "guibar\n"
    "guiradio \"Yellow\" playerteamcolor 2 \"playerteamcolor 2\"\n"
    "guibar\n"
    "guiradio \"Red\" playerteamcolor 3 \"playerteamcolor 3\"\n"
    "guibar\n"
    "guiradio \"Gray\" playerteamcolor 4 \"playerteamcolor 4\"\n"
    "guibar\n"
    "guiradio \"Magenta\" playerteamcolor 5 \"playerteamcolor 5\"\n"
    "guibar\n"
    "guiradio \"Orange\" playerteamcolor 6 \"playerteamcolor 6\"\n"
    "guibar\n"
    "guiradio \"White\" playerteamcolor 7 \"playerteamcolor 7\"\n"
    "guibar\n"
    "guiradio \"Dim\" playerteamcolor 8 \"playerteamcolor 8\"\n"
    "guibar\n"
    "guiradio \"Cyan\" playerteamcolor 9 \"playerteamcolor 9\"\n"
    "]\n"
    "guistrut 1\n"

    "guitext \"Enemy team text color:\" 0\n"
    "guilist [\n"
    "guiradio \"Green\" enemyteamcolor 0 \"enemyteamcolor 0\"\n"
    "guibar\n"
    "guiradio \"Blue\" enemyteamcolor 1 \"enemyteamcolor 1\"\n"
    "guibar\n"
    "guiradio \"Yellow\" enemyteamcolor 2 \"enemyteamcolor 2\"\n"
    "guibar\n"
    "guiradio \"Red\" enemyteamcolor 3 \"enemyteamcolor 3\"\n"
    "guibar\n"
    "guiradio \"Gray\" enemyteamcolor 4 \"enemyteamcolor 4\"\n"
    "guibar\n"
    "guiradio \"Magenta\" enemyteamcolor 5 \"enemyteamcolor 5\"\n"
    "guibar\n"
    "guiradio \"Orange\" enemyteamcolor 6 \"enemyteamcolor 6\"\n"
    "guibar\n"
    "guiradio \"White\" enemyteamcolor 7 \"enemyteamcolor 7\"\n"
    "guibar\n"
    "guiradio \"Dim\" enemyteamcolor 8 \"enemyteamcolor 8\"\n"
    "guibar\n"
    "guiradio \"Cyan\" enemyteamcolor 9 \"enemyteamcolor 9\"\n"
    "]\n"
    "guistrut 1\n"

    "guitext \"Chat color:\" 0\n"
    "guilist [\n"
    "guiradio \"Green\" chatcolor 0 \"chatcolor 0\"\n"
    "guibar\n"
    "guiradio \"Blue\" chatcolor 1 \"chatcolor 1\"\n"
    "guibar\n"
    "guiradio \"Yellow\" chatcolor 2 \"chatcolor 2\"\n"
    "guibar\n"
    "guiradio \"Red\" chatcolor 3 \"chatcolor 3\"\n"
    "guibar\n"
    "guiradio \"Gray\" chatcolor 4 \"chatcolor 4\"\n"
    "guibar\n"
    "guiradio \"Magenta\" chatcolor 5 \"chatcolor 5\"\n"
    "guibar\n"
    "guiradio \"Orange\" chatcolor 6 \"chatcolor 6\"\n"
    "guibar\n"
    "guiradio \"White\" chatcolor 7 \"chatcolor 7\"\n"
    "guibar\n"
    "guiradio \"Dim\" chatcolor 8 \"chatcolor 8\"\n"
    "guibar\n"
    "guiradio \"Cyan\" chatcolor 9 \"chatcolor 9\"\n"
    "]\n"
    "guistrut 1\n"

    "guitext \"Team chat color:\" 0\n"
    "guilist [\n"
    "guiradio \"Green\" teamchatcolor 0 \"teamchatcolor 0\"\n"
    "guibar\n"
    "guiradio \"Blue\" teamchatcolor 1 \"teamchatcolor 1\"\n"
    "guibar\n"
    "guiradio \"Yellow\" teamchatcolor 2 \"teamchatcolor 2\"\n"
    "guibar\n"
    "guiradio \"Red\" teamchatcolor 3 \"teamchatcolor 3\"\n"
    "guibar\n"
    "guiradio \"Gray\" teamchatcolor 4 \"teamchatcolor 4\"\n"
    "guibar\n"
    "guiradio \"Magenta\" teamchatcolor 5 \"teamchatcolor 5\"\n"
    "guibar\n"
    "guiradio \"Orange\" teamchatcolor 6 \"teamchatcolor 6\"\n"
    "guibar\n"
    "guiradio \"White\" teamchatcolor 7 \"teamchatcolor 7\"\n"
    "guibar\n"
    "guiradio \"Dim\" teamchatcolor 8 \"teamchatcolor 8\"\n"
    "guibar\n"
    "guiradio \"Cyan\" teamchatcolor 9 \"teamchatcolor 9\"\n"
    "]\n"
    "guistrut 1\n"

    "guitext \"Game messages color:\" 0\n"
    "guilist [\n"
    "guiradio \"Green\" gamemessagescolor 0 \"gamemessagescolor 0\"\n"
    "guibar\n"
    "guiradio \"Blue\" gamemessagescolor 1 \"gamemessagescolor 1\"\n"
    "guibar\n"
    "guiradio \"Yellow\" gamemessagescolor 2 \"gamemessagescolor 2\"\n"
    "guibar\n"
    "guiradio \"Red\" gamemessagescolor 3 \"gamemessagescolor 3\"\n"
    "guibar\n"
    "guiradio \"Gray\" gamemessagescolor 4 \"gamemessagescolor 4\"\n"
    "guibar\n"
    "guiradio \"Magenta\" gamemessagescolor 5 \"gamemessagescolor 5\"\n"
    "guibar\n"
    "guiradio \"Orange\" gamemessagescolor 6 \"gamemessagescolor 6\"\n"
    "guibar\n"
    "guiradio \"White\" gamemessagescolor 7 \"gamemessagescolor 7\"\n"
    "guibar\n"
    "guiradio \"Dim\" gamemessagescolor 8 \"gamemessagescolor 8\"\n"
    "guibar\n"
    "guiradio \"Cyan\" gamemessagescolor 9 \"gamemessagescolor 9\"\n"
    "]\n"
    "guistrut 1\n"


    "guitab \"HUDSelect\"\n"

    "guititle \"Warning: All current HUD settings will be reset to the selected HUD settings\"\n"
    "guistrut 1\n"
    "guibar\n"
    "guistrut 1\n"
    "guibutton \"Default HUD\" \"hudold\" \n"
    "guistrut 1\n"
    "guibutton \"Default extended HUD\" \"hudoldextended\" \n"
    "guistrut 1\n"
    "guibutton \"New customisable HUD (example1)\" \"hudnew1\"\n"
    "guistrut 1\n"
    "guibutton \"New customisable HUD (example2)\" \"hudnew2\"\n"
    "guistrut 1\n"
    "guibutton \"New customisable HUD (example3)\" \"hudnew3\"\n"
    "guistrut 1\n"
    "guibar\n"
    "guistrut 1\n"


    "guitab \"Networking\"\n"

    "guititle \"Note: Intended to be used on servers with low packets delay support\"\n"
    "guistrut 1\n"
    "guitext \"Position packet delay (less values are smoothing client's position lags):\" 0\n"
    "guislider positionpacketdelay\n"
    "guistrut 1\n"
    "guicheckbox \"Disable enet limits (fixes unnecessary client's position packet drops)\" disable_enet_limits\n"
    "guistrut 1\n"

"] \"General\" \n";

const char *gamepad_settings_gui =
"newgui gamepad_settings [\n"
    "guicheckbox \"Enable gamepad\" gamepad\n"
    "guistrut 1\n"
    "if (getnumpads) [\n"
        "loop i (getnumpads) [\n"
            "guiradio (getpadname $i) selectedpad $i (concat selectedpad $i)\n"
        "]\n"
        "guistrut 2\n"
        "guititle \"Note: You can set gamepad button bindings via the standard menu.\"\n"
        "guititle \"Use right stick to move a cursor or look around in the game.\"\n"
        "guititle \"Left stick emulates additional D-Pad, and can be used to bind commands.\"\n"
        "guititle \"In UI right stick click is mouse1, B is mouse2, logo(guide) button is esc.\"\n"
    "] [\n"
        "if $gamepad [\n"
            "guititle \"No gamepads found.\"\n"
        "]\n"
    "]\n"
    "guititle \"Use gamecontrollerdb.txt as SDL2 gamepad settings in the game config directory.\"\n"

    "guitab \"Rumble\"\n"
    "guicheckbox \"Enable rumble\" haptic\n"
    "guistrut 1\n"
    "if (getnumhaptics) [\n"
        "loop i (getnumhaptics) [\n"
            "guilist [\n"
            "guitext (gethapticname $i) 0\n"
            "guibar\n"
            "guiradio \"Off\" (makehapticmodename $i) 0 (concat (makehapticmodename $i) 0) \n"
            "guibar\n"
            "guiradio \"Shoot\" (makehapticmodename $i) 1 (concat (makehapticmodename $i) 1) \n"
            "guibar\n"
            "guiradio \"Damage\" (makehapticmodename $i) 2 (concat (makehapticmodename $i) 2) \n"
            "guibar\n"
            "guiradio \"Both\" (makehapticmodename $i) 3 (concat (makehapticmodename $i) 3) \n"
            "]\n"
            "guislider (makehapticcapname $i)\n"
            "guistrut 1\n"
        "]\n"
    "] [\n"
        "if $haptic [\n"
            "guitext \"No rumble devices found.\" 0\n"
        "]\n"
     "]\n"
    "guitab \"Advanced\"\n"
    "guitext \"Stick look sensitivity:\" 0\n"
    "guislider sticksens\n"
    "guistrut 1\n"
    "guitext \"Stick UI sensitivity:\" 0\n"
    "guislider guisticksens\n"
    "guistrut 1\n"
    "guitext \"Stick sensitivity curve:\" 0\n"
    "guislider sticksenscurve\n"
    "guistrut 1\n"
    "guitext \"Stick deadzone:\" 0\n"
    "guislider stickdeadzone\n"
    "guistrut 1\n"
    "guitext \"Trigger buttons emulation level:\" 0\n"
    "guislider triggerlevel\n"
    "guistrut 1\n"
    "guitext \"Stick buttons emulation level:\" 0\n"
    "guislider stickpadlevel\n"
    "guistrut 1\n"

"] \"Gamepad\" \n";

const char *hud_settings_gui =
"newgui hud_settings [\n"
    "guicheckbox \"Colored health\" coloredhealth\n"
    "guicheckbox \"Colored ammo\" coloredammo\n"
    "guistrut 1\n"

    "guititle \"HDPI settings\"\n"
    "guitext \"New HUD scale:\" 0\n"
    "guislider hudscale\n"
    "guistrut 1\n"

    "guitext \"Text scale:\" 0\n"
    "guislider textscale\n"
    "guistrut 1\n"

    "guitab \"Lagometer\"\n"

    "guilist [\n"
    "guicheckbox \"Show lagomter\" lagometer\n"
    "guibar\n"
    "guicheckbox \"Disable background\" lagometernobg\n"
    "guibar\n"
    "guicheckbox \"Disable when not connected\" lagometerdisablelocal\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" lagometerdisablewithgui\n"
    "]\n"
    "guilist [\n"
    "guicheckbox \"Show ping in lagomter\" lagometershowping\n"
    "guibar\n"
    "guicheckbox \"Only ping in self lagometer\" lagometeronlypingself\n"
    "]\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y):\" 0\n"
    "guilist [\n"
    "guitext \"X offset start\"\n"
    "guibar\n"
    "guiradio \"Left\" lagometerpos_start_x -1 \"lagometerpos_start_x -1\"\n"
    "guibar\n"
    "guiradio \"Center\" lagometerpos_start_x 0 \"lagometerpos_start_x 0\"\n"
    "guibar\n"
    "guiradio \"Right\" lagometerpos_start_x 1 \"lagometerpos_start_x 1\"\n"
    "]\n"
    "guislider lagometerpos_x\n"
    "guislider lagometerpos_y\n"
    "guistrut 1\n"

    "guitext \"Lagometer number of columns:\" 0\n"
    "guislider lagometerlen\n"
    "guitext \"Lagometer column width:\" 0\n"
    "guislider lagometercolsz\n"
    "guistrut 1\n"

    "guitext \"Lagometer height:\" 0\n"
    "guislider lagometerheight\n"
    "guitext \"Lagometer ping size:\" 0\n"
    "guislider lagometerpingsz\n"
    "guistrut 1\n"


    "guitab \"Ammobar\"\n"

    "guilist [\n"
    "guicheckbox \"Show ammobar\" ammobar\n"
    "guibar\n"
    "guicheckbox \"Don't show in insta modes\" ammobardisableininsta\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" ammobardisablewithgui\n"
    "]\n"
    "guilist [\n"
    "guicheckbox \"Horizontal ammobar\" ammobarhorizontal\n"
    "guibar\n"
    "guicheckbox \"Transparent empty weapons\" ammobarfilterempty\n"
    "guibar\n"
    "]\n"
    "guilist [\n"
    "guitext \"Icons position\"\n"
    "guibar\n"
    "guiradio \"Left\" ammobariconspos -1 \"ammobariconspos -1\"\n"
    "guibar\n"
    "guiradio \"Top\" ammobariconspos 0 \"ammobariconspos 0\"\n"
    "guibar\n"
    "guiradio \"Right\" ammobariconspos 1 \"ammobariconspos 1\"\n"
    "]\n"
    "guistrut 1\n"

    "guitext \"Size:\" 0\n"
    "guislider ammobarsize\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y):\" 0\n"
    "guilist [\n"
    "guitext \"X offset start\"\n"
    "guibar\n"
    "guiradio \"Left\" ammobaroffset_start_x -1 \"ammobaroffset_start_x -1\"\n"
    "guibar\n"
    "guiradio \"Center\" ammobaroffset_start_x 0 \"ammobaroffset_start_x 0\"\n"
    "guibar\n"
    "guiradio \"Right\" ammobaroffset_start_x 1 \"ammobaroffset_start_x 1\"\n"
    "]\n"
    "guislider ammobaroffset_x\n"
    "guislider ammobaroffset_y\n"
    "guistrut 1\n"

    "guitext \"Selected gun background (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider ammobarselectedcolor_r\n"
    "guislider ammobarselectedcolor_g\n"
    "guislider ammobarselectedcolor_b\n"
    "guislider ammobarselectedcolor_a\n"


    "guitab \"Clock\"\n"

    "guilist [\n"
    "guicheckbox \"Show clock\" gameclock\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" gameclockdisablewithgui\n"
    "]\n"
    "guistrut 1\n"

    "guitext \"Size:\" 0\n"
    "guislider gameclocksize\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y):\" 0\n"
    "guilist [\n"
    "guitext \"X offset start\"\n"
    "guibar\n"
    "guiradio \"Left\" gameclockoffset_start_x -1 \"gameclockoffset_start_x -1\"\n"
    "guibar\n"
    "guiradio \"Center\" gameclockoffset_start_x 0 \"gameclockoffset_start_x 0\"\n"
    "guibar\n"
    "guiradio \"Right\" gameclockoffset_start_x 1 \"gameclockoffset_start_x 1\"\n"
    "]\n"
    "guislider gameclockoffset_x\n"
    "guislider gameclockoffset_y\n"


    "guitab \"\"\n"

    "guitext \"Clock text color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider gameclockcolor_r\n"
    "guislider gameclockcolor_g\n"
    "guislider gameclockcolor_b\n"
    "guislider gameclockcolor_a\n"
    "guistrut 1\n"

    "guitext \"Clock background color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider gameclockcolorbg_r\n"
    "guislider gameclockcolorbg_g\n"
    "guislider gameclockcolorbg_b\n"
    "guislider gameclockcolorbg_a\n"


    "guitab \"Scores\"\n"

    "guilist [\n"
    "guicheckbox \"Show hud scores\" hudscores\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" hudscoresdisablewithgui\n"
    "]\n"
    "guicheckbox \"Vertical scores\" hudscoresvertical\n"
    "guistrut 1\n"

    "guitext \"Size:\" 0\n"
    "guislider hudscoressize\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y):\" 0\n"
    "guilist [\n"
    "guitext \"X offset start\"\n"
    "guibar\n"
    "guiradio \"Left\" hudscoresoffset_start_x -1 \"hudscoresoffset_start_x -1\"\n"
    "guibar\n"
    "guiradio \"Center\" hudscoresoffset_start_x 0 \"hudscoresoffset_start_x 0\"\n"
    "guibar\n"
    "guiradio \"Right\" hudscoresoffset_start_x 1 \"hudscoresoffset_start_x 1\"\n"
    "]\n"
    "guislider hudscoresoffset_x\n"
    "guislider hudscoresoffset_y\n"
    "guistrut 1\n"

    "guitext \"Player score text color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider hudscoresplayercolor_r\n"
    "guislider hudscoresplayercolor_g\n"
    "guislider hudscoresplayercolor_b\n"
    "guislider hudscoresplayercolor_a\n"


    "guitab \"\"\n"

    "guitext \"Player score background color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider hudscoresplayercolorbg_r\n"
    "guislider hudscoresplayercolorbg_g\n"
    "guislider hudscoresplayercolorbg_b\n"
    "guislider hudscoresplayercolorbg_a\n"
    "guistrut 1\n"

    "guitext \"Enemy score text color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider hudscoresenemycolor_r\n"
    "guislider hudscoresenemycolor_g\n"
    "guislider hudscoresenemycolor_b\n"
    "guislider hudscoresenemycolor_a\n"
    "guistrut 1\n"

    "guitext \"Enemy score background color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider hudscoresenemycolorbg_r\n"
    "guislider hudscoresenemycolorbg_g\n"
    "guislider hudscoresenemycolorbg_b\n"
    "guislider hudscoresenemycolorbg_a\n"


    "guitab \"HP\"\n"

    "guititle \"Warning: Settings have effect only when new HUD is enabled\"\n"
    "guicheckbox \"Enable new HUD\" newhud\n"
    "guistrut 1\n"

    "guititle \"New HUD HP/Armour settings\"\n"
    "guilist [\n"
    "guicheckbox \"Don't show in insta modes\" newhud_hpdisableininsta\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" newhud_hpdisablewithgui\n"
    "]\n"

    "guitext \"Size:\" 0\n"
    "guislider newhud_hpssize\n"
    "guitext \"Icon size:\" 0\n"
    "guislider newhud_hpiconssize\n"
    "guitext \"Icon separator size:\" 0\n"
    "guislider newhud_hpgap\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y):\" 0\n"
    "guislider newhud_hppos_x\n"
    "guislider newhud_hppos_y\n"


    "guitab \"Ammo\"\n"

    "guititle \"Warning: Settings have effect only when new HUD is enabled\"\n"
    "guicheckbox \"Enable new HUD\" newhud\n"
    "guistrut 1\n"
    
    "guititle \"New HUD Ammo settings\"\n"
    "guilist [\n"
    "guicheckbox \"Don't show ammo\" newhud_ammodisable\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" newhud_ammodisablewithgui\n"
    "]\n"
    "guilist [\n"
    "guitext \"Insta modes behaviour\"\n"
    "guibar\n"
    "guiradio \"Show in all modes\" newhud_ammodisableininsta 0 \"newhud_ammodisableininsta 0\"\n"
    "guibar\n"
    "guiradio \"Show only in insta modes\" newhud_ammodisableininsta -1 \"newhud_ammodisableininsta -1\"\n"
    "guibar\n"
    "guiradio \"Show in non-insta modes\" newhud_ammodisableininsta 1 \"newhud_ammodisableininsta 1\"\n"
    "]\n"
    "guitext \"Size:\" 0\n"
    "guislider newhud_ammosize\n"
    "guitext \"Icon size:\" 0\n"
    "guislider newhud_ammoiconssize\n"
    "guitext \"Icon separator size:\" 0\n"
    "guislider newhud_ammogap\n"
    "guistrut 1\n"

    "guitext \"Ammo offset (X/Y):\" 0\n"
    "guislider newhud_ammopos_x\n"
    "guislider newhud_ammopos_y\n"


    "guitab \"Spectator\"\n"

    "guititle \"Warning: Settings have effect only when new HUD is enabled\"\n"
    "guicheckbox \"Enable new HUD\" newhud\n"
    "guistrut 1\n"
    
    "guititle \"New HUD spectator settings\"\n"
    "guicheckbox \"Disable with GUI\" newhud_spectatorsdisablewithgui\n"
    "guicheckbox \"No privilege colors\" newhud_spectatorsnocolor\n"
    "guitext \"Size:\" 0\n"
    "guislider newhud_spectatorsize\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y):\" 0\n"
    "guilist [\n"
    "guitext \"X offset start\"\n"
    "guibar\n"
    "guiradio \"Left\" newhud_spectatorpos_start_x -1 \"newhud_spectatorpos_start_x -1\"\n"
    "guibar\n"
    "guiradio \"Center\" newhud_spectatorpos_start_x 0 \"newhud_spectatorpos_start_x 0\"\n"
    "guibar\n"
    "guiradio \"Right\" newhud_spectatorpos_start_x 1 \"newhud_spectatorpos_start_x 1\"\n"
    "]\n"
    "guislider newhud_spectatorpos_x\n"
    "guislider newhud_spectatorpos_y\n"


    "guitab \"Items\"\n"

    "guititle \"Warning: Settings have effect only when new HUD is enabled\"\n"
    "guicheckbox \"Enable new HUD\" newhud\n"
    "guistrut 1\n"
    
    "guititle \"New HUD items settings\"\n"
    "guicheckbox \"Disable with GUI\" newhud_itemsdisablewithgui\n"
    "guitext \"Size:\" 0\n"
    "guislider newhud_itemssize\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y):\" 0\n"
    "guilist [\n"
    "guicheckbox \"Use reverse X offset\" newhud_itemspos_reverse_x\n"
    "guibar\n"
    "guicheckbox \"Center first item\" newhud_itemspos_centerfirst\n"
    "]\n"
    "guislider newhud_itemspos_x\n"
    "guislider newhud_itemspos_y\n"

    
    "guitab \"Other\"\n"

    "guititle \"Warning: Settings have effect only when new HUD is enabled\"\n"
    "guicheckbox \"Enable new HUD\" newhud\n"
    "guistrut 1\n"
    
    "guitext \"Minicon Y offset:\" 0\n"
    "guislider newhud_miniconoffset\n"
    "guistrut 1\n"

    "guitext \"Minicon lines:\" 0\n"
    "guislider newhud_miniconsize\n"
    "guitext \"Minicon width:\" 0\n"
    "guislider newhud_miniconwidth\n"
    "guistrut 1\n"

    "guitext \"System output Y offset:\" 0\n"
    "guislider newhud_sysoutoffset\n"
    "guicheckbox \"Show game HUD in the last line\" newhud_sysoutgamehudlast\n"
    "guistrut 1\n"

    "guitext \"GUI height limit with HUD:\" 0\n"
    "guislider newhud_abovehud\n"
    "guistrut 1\n"

"] \"General\"\n";


const char *extended_menus =
"currentsearch = \"\"\n"
"currenttitle = \"\"\n"
"currentfilters = \"\"\n"
"setsearch = [\n"
    "textfocus \"#patterneditor\"\n"
    "textclear\n"
    "currenttitle = (unescape $currentsearch)\n"
    "currentfilters = (getplayersearch (stringify $currentsearch))\n"
    "setguieditorcontent \"#patterneditor\" (unescape $currentfilters)\n"
"]\n"
"newgui playersearches [\n"
    "guistayopen [\n"
        "local ntitle entitle\n"
        "guilist [\n"
            "guispring\n"
            "guibutton \"new search\" [clearsearchdata; currentsearch = \"\"; currenttitle = \"\"; showgui players]\n"
            "guispring\n"
        "]\n"
        "guibar\n"
        "looplist s $savedsearches [\n"
            "guilist [\n"
                "ntitle = (at $s 0)\n"
                "entitle = (escape $ntitle)\n"
                "guibutton (unescape $ntitle) [clearsearchdata; currentsearch = @entitle; currenttitle = (unescape @entitle); showgui players]\n"
            "]\n"
        "]\n"
    "]\n"
"] \"searches\"\n"
"newgui editplayersearch [\n"
    "keepsearching\n"
    "guistayopen [\n"
        "guilist [\n"
            "local ntitle nsearch ensearch\n"
            "guitext \"title \"\n"
            "ntitle = $currenttitle\n"
            "guifield ntitle 50 [currenttitle = (substr $ntitle 0 50)]\n"
            "guistrut 1\n"
            "nsearch = (escape $currenttitle)\n"
            "ensearch = (escape $nsearch)\n"
            "if (&& (!=s $currentsearch \"\") (!=s $currenttitle \"\") (|| (=s (stringify $currentsearch) $nsearch) (! (playersearchexists $nsearch)))) [\n"
                "guibutton \"save changes  \" [textfocus \"#patterneditor\"; currentfilters = (escape (textshow)); updateplayersearch $currentsearch $currentfilters @ensearch; currentsearch = (at (escape $currenttitle)); hidegui editplayersearch] \"action\"\n"
                "guibutton \"delete search  \" [deleteplayersearch $currentsearch; currenttitle = \"\"; currentsearch = \"\"; hidegui editplayersearch] \"exit\"\n"
             "]\n"
             "if (&& (=s $currentsearch \"\") (!=s $currenttitle \"\") (! (playersearchexists $nsearch))) [\n"
                "guibutton \"save changes  \" [textfocus \"#patterneditor\"; currentfilters = (escape (textshow)); updateplayersearch @nsearch $currentfilters @ensearch; currentsearch = (at (escape $currenttitle)); hidegui editplayersearch] \"action\"\n"
             "]\n"
        "]\n"
        "guistrut 1\n"
        "guilist [\n"
            "guitext \"patterns to match names against (whitespace separated)\"\n"
        "]\n"
        "guieditor #patterneditor 100 10\n"
        "guilist [\n"
        "guibutton \"copy \" [textfocus \"#patterneditor\"; (textcopy)]\n"
        "guibutton \"paste \" [textfocus \"#patterneditor\"; (textpaste)]\n"
        "guibutton \"select all\" [textfocus \"#patterneditor\"; (textselectall)]\n"
        "]\n"
    "]\n"
"] \"search editor\"\n"
"newgui players [\n"
    "guistayopen [\n"
         "guiplayers (unescape $currentsearch)\n"
    "]\n"
"] \n"
"newgui serverpreview [\n"
    "guistayopen [\n"
         "guiserverpreview\n"
    "]\n"
"] \"preview\" \n"
"newgui demoslist [\n"
    "guistayopen [\n"
         "guidemoslist\n"
    "]\n"
"] \"demos\" \n";


const char *extended_helpers =
"stringify = [\n"
    "concatword \"^\"\"$arg1\"^\"\"\n"
"]\n"
"unstringify = [\n"
    "at [@arg1]\n"
"]\n"
"updateplayersearch = [\n"
    "if (!=s $arg1 \"\") [\n"
        "local foundname i node sname\n"
        "sname = (stringify $arg1)\n"
        "foundname = -1\n"
        "i = 0\n"
        "looplist entry $savedsearches [\n"
            "if (=s $sname (stringify (at $entry 0))) [\n"
                "foundname = $i\n"
            "]\n"
            "i = (+ $i 1)\n"
        "]\n"
        "if (!=s $arg3 \"\") [\n"
            "sname = $arg3\n"
        "]\n"
        "node = [[@@sname @@arg2]]\n"
        "if (= $foundname -1) [\n"
            "(overwritesearches (listsplice $savedsearches $node $i 0))\n"
        "] [\n"
            "(overwritesearches (listsplice $savedsearches $node $foundname 1))\n"
        "]\n"
    "]\n"
"] \n"
"deleteplayersearch = [\n"
    "if (!=s $arg1 \"\") [\n"
        "local foundname i sname\n"
        "sname = $arg1\n"
        "foundname = -1\n"
        "i = 0\n"
        "looplist entry $savedsearches [\n"
            "if (=s $sname (at $entry 0)) [\n"
                "foundname = $i\n"
            "]\n"
            "i = (+ $i 1)\n"
        "]\n"
        "if (!= $foundname -1) [\n"
            "(overwritesearches (listsplice $savedsearches [] $foundname 1))\n"
        "]\n"
    "]\n"
"] \n"
"getplayersearch = [\n"
    "local res sname\n"
    "res = \"\"\n"
    "if (!=s $arg1 \"\") [\n"
        "sname = (at $arg1)\n"
        "looplist entry $savedsearches [\n"
            "if (=s $sname (at $entry 0)) [\n"
                "res = (at $entry 1)\n"
            "]\n"
        "]\n"
    "]\n"
    "result $res\n"
"] \n"
"playersearchexists = [\n"
    "local res sname\n"
    "res = 0\n"
    "if (!=s $arg1 \"\") [\n"
        "sname = (at $arg1)\n"
        "looplist entry $savedsearches [\n"
            "if (=s $sname (at $entry 0)) [\n"
                "res = 1\n"
            "]\n"
        "]\n"
    "]\n"
    "result $res\n"
"] \n";


const char *new_main_menu =
"if $usenewmainmenu [\n"
"newgui main [\n"
"    guilist [\n"
"        guitext \"name: \" (playermodelicon)\n"
"        newname = (getname)\n"
"        guifield newname 15 [name $newname]\n"
"    ]\n"
"    guibutton (concat \"model:\" (playermodelname)) [guirolloveraction = (playermodelbutton $playermodel); showgui playermodel] (playermodelicon)\n"
"    guilist [\n"
"        guibutton \"crosshair: \" [showgui crosshair] (playermodelicon)\n"
"        guiimage (getcrosshair) [showgui crosshair] 0.5\n"
"    ]\n"
"    guibar\n"
"    guibutton \"server browser..\"  \"showgui servers\"\n"
"    guibutton \"players..\"  \"showgui playersearches\"\n"
"    guibutton \"demos..\"  [updatedemoslist; showgui demoslist]\n"
"    if (isconnected) [\n"
"        guibar\n"
"        if (|| $editing (m_edit (getmode))) [\n"
"            guibutton \"editing..\" \"showgui editing\"\n"
"        ]\n"
"        guibutton \"vote game mode / map..\" \"showgui gamemode\"\n"
"        guibutton \"switch team\" [if (strcmp (getteam) \"good\") [team evil] [team good]]\n"
"        guibutton \"toggle spectator\" [spectator (! (isspectator (getclientnum)))] \"spectator\"\n"
"        guibutton \"master..\" [showgui master]\n"
"        guibar\n"
"        guibutton \"options..\"  \"showgui options\"\n"
"        guibutton \"more options..\"  \"showgui extended_settings\"\n"
"        guibutton \"gamepad..\"    \"showgui gamepad_settings\"\n"
"        guibutton \"hud settings..\"  \"showgui hud_settings\"\n"
"        guibutton \"disconnect\" \"disconnect\"         \"exit\"\n"
"    ] [\n"
"        guibutton \"bot match..\"      \"showgui botmatch\"\n"
"        guibutton \"campaign..\"       \"showgui campaign\"\n"
"        guibar\n"
"        guibutton \"options..\"        \"showgui options\"\n"
"        guibutton \"more options..\"    \"showgui extended_settings\"\n"
"        guibutton \"gamepad..\"    \"showgui gamepad_settings\"\n"
"        guibutton \"hud settings..\"    \"showgui hud_settings\"\n"
"        guibutton \"about..\"          \"showgui about\"\n"
"        guibutton \"quit\"             \"quit\"                 \"exit\"\n"
"    ]\n"
"] 0\n"
"]";


const char *hit_sound =
"registersound aard/bang 255\n";


const char *game_scripts[] = { extended_settings_gui,
                               hud_settings_gui,
                               hud_old,
                               hud_old_extended,
                               hud_new1,
                               hud_new2,
                               hud_new3,
                               extended_helpers,
                               extended_menus,
                               new_main_menu,
                               hit_sound,
                               gamepad_settings_gui,
                               0 };


#endif
