#ifndef __EXTENDEDSCRIPTS_H__
#define __EXTENDEDSCRIPTS_H__

const char *hud_old =
"hudold = [\n"

    "ammobar 0\n"
    "ammobardisablewithgui 0\n"
    "ammobarfilterempty 0\n"
    "ammobarhorizontal 0\n"
    "ammobaroffset_x 30\n"
    "ammobaroffset_y 500\n"
    "ammobarselectedbg 1\n"
    "ammobarselectedcolor_a 150\n"
    "ammobarselectedcolor_b 255\n"
    "ammobarselectedcolor_g 200\n"
    "ammobarselectedcolor_r 100\n"
    "ammobarsize 5\n"
    "gameclock 0\n"
    "gameclockcolor_a 255\n"
    "gameclockcolor_b 255\n"
    "gameclockcolor_g 255\n"
    "gameclockcolor_r 255\n"
    "gameclockdisablewithgui 0\n"
    "gameclockoffset_reverse_x 1\n"
    "gameclockoffset_x 10\n"
    "gameclockoffset_y 300\n"
    "gameclocksize 5\n"
    "hudscores 0\n"
    "hudscoresdisablewithgui 0\n"
    "hudscoresenemycolor_a 255\n"
    "hudscoresenemycolor_b 0\n"
    "hudscoresenemycolor_g 0\n"
    "hudscoresenemycolor_r 255\n"
    "hudscoresoffset_reverse_x 1\n"
    "hudscoresoffset_x 10\n"
    "hudscoresoffset_y 350\n"
    "hudscoresplayercolor_a 255\n"
    "hudscoresplayercolor_b 255\n"
    "hudscoresplayercolor_g 255\n"
    "hudscoresplayercolor_r 0\n"
    "hudscoressize 5\n"
    "newhud 0\n"
    "newhud_ammoiconssize 60\n"
    "newhud_ammopos_x 580\n"
    "newhud_ammopos_y 960\n"
    "newhud_ammosize 30\n"
    "newhud_hpiconssize 60\n"
    "newhud_hppos_x 420\n"
    "newhud_hppos_y 960\n"
    "newhud_hpssize 30\n"
    "newhud_itemspos_reverse_x 1\n"
    "newhud_itemspos_x 10\n"
    "newhud_itemspos_y 870\n"
    "newhud_itemssize 14\n"
    "newhud_miniconoffset 0\n"
    "newhud_miniconsize 6\n"
    "newhud_miniconwidth 30\n"
    "newhud_spectatorpos_x 500\n"
    "newhud_spectatorpos_y 110\n"
    "newhud_spectatorsize 5\n"
"]\n";


const char *extended_settings_gui =
"newgui extended_settings [\n"

    "guicheckbox \"No sparks for hitscan weapons\" reducesparks\n"
    "guicheckbox \"No explosion animation\" reduceexplosions\n"
    "guicheckbox \"No explosion debris\" removeexplosionsdebris\n"
    "guicheckbox \"Colored health\" coloredhealth\n"
    "guicheckbox \"Colored ammo\" coloredammo\n"
    "guicheckbox \"Use following player team\" usefollowingplayerteam\n"
    "guicheckbox \"Log players stats on game end\" dumpstatsongameend\n"
    "guicheckbox \"Show servers preview\" showserverpreviews\n"
    "guistrut 1\n"

    "guitext \"Smoke density (for rockets and grenades):\" 0\n"
    "guislider smokefps\n"

    "guitab \"Scoreboard\"\n"
    "guicheckbox \"Show flags scored\" showflags\n"
    "guilist [\n"
    "guicheckbox \"Show frags in all modes\" showfrags\n"
    "guibar\n"
    "guicheckbox \"Show net in frags field\" shownetfrags\n"
    "guibar\n"
    "guicheckbox \"Net colors\" netfragscolors\n"
    "]\n"
    "guilist [\n"
    "guicheckbox \"Show damage dealt\" showdamagedealt\n"
    "guibar\n"
    "guicheckbox \"Show net in damage field\" shownetdamage\n"
    "guibar\n"
    "guicheckbox \"Net colors\" netdamagecolors\n"
    "]\n"
    "guicheckbox \"Show accuracy\" showacc\n"

    "guitab \"Clock\"\n"

    "guilist [\n"
    "guicheckbox \"Show clock\" gameclock\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" gameclockdisablewithgui\n"
    "]\n"
    "guitext \"Size:\" 0\n"
    "guislider gameclocksize\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y)^f~:\" 0\n"
    "guicheckbox \"Use reverse X offset\" gameclockoffset_reverse_x\n"
    "guislider gameclockoffset_x\n"
    "guislider gameclockoffset_y\n"
    "guistrut 1\n"

    "guitext \"Color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider gameclockcolor_r\n"
    "guislider gameclockcolor_g\n"
    "guislider gameclockcolor_b\n"
    "guislider gameclockcolor_a\n"

    "guitab \"HudScores\"\n"

    "guilist [\n"
    "guicheckbox \"Show hud scores\" hudscores\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" hudscoresdisablewithgui\n"
    "]\n"

    "guitext \"Size:\" 0\n"
    "guislider hudscoressize\n"
    "guistrut 1\n"

    "guitext \"Offset (X/Y)^f~:\" 0\n"
    "guicheckbox \"Use reverse X offset\" hudscoresoffset_reverse_x\n"
    "guislider hudscoresoffset_x\n"
    "guislider hudscoresoffset_y\n"
    "guistrut 1\n"

    "guitab \"Scores Colors\"\n"

    "guitext \"Player color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider hudscoresplayercolor_r\n"
    "guislider hudscoresplayercolor_g\n"
    "guislider hudscoresplayercolor_b\n"
    "guislider hudscoresplayercolor_a\n"
    "guistrut 1\n"

    "guitext \"Enemy color (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider hudscoresenemycolor_r\n"
    "guislider hudscoresenemycolor_g\n"
    "guislider hudscoresenemycolor_b\n"
    "guislider hudscoresenemycolor_a\n"

    "guitab \"Ammobar\"\n"

    "guilist [\n"
    "guicheckbox \"Show ammobar\" ammobar\n"
    "guibar\n"
    "guicheckbox \"Disable with GUI\" ammobardisablewithgui\n"
    "]\n"
    "guicheckbox \"Horizontal ammobar\" ammobarhorizontal\n"
    "guicheckbox \"Don't show empty weapons\" ammobarfilterempty\n"
    "guistrut 1\n"

    "guitext \"Size:\" 0\n"
    "guislider ammobarsize\n"
    "guistrut 1\n"
    
    "guitext \"Offset (X/Y):\" 0\n"
    "guislider ammobaroffset_x\n"
    "guislider ammobaroffset_y\n"
    "guistrut 1\n"

    "guicheckbox \"Draw selected gun background\" ammobarselectedbg\n"
    "guitext \"Selected gun background (^f3R^f~/^f0G^f~/^f1B^f~/^f4A^f~):\" 0\n"
    "guislider ammobarselectedcolor_r\n"
    "guislider ammobarselectedcolor_g\n"
    "guislider ammobarselectedcolor_b\n"
    "guislider ammobarselectedcolor_a\n"

    "guitab \"New HUD\"\n"
    "guicheckbox \"Enable new HUD\" newhud\n"
    "guitext \"HP/Armour size:\" 0\n"
    "guislider newhud_hpssize\n"
    "guitext \"Amour icon size:\" 0\n"
    "guislider newhud_hpiconssize\n"
    "guitext \"HP/Armour offset (X/Y):\" 0\n"
    "guislider newhud_hppos_x\n"
    "guislider newhud_hppos_y\n"

    "guitext \"Ammo size:\" 0\n"
    "guislider newhud_ammosize\n"
    "guitext \"Ammo icon size:\" 0\n"
    "guislider newhud_ammoiconssize\n"
    "guitext \"Ammo offset (X/Y):\" 0\n"
    "guislider newhud_ammopos_x\n"
    "guislider newhud_ammopos_y\n"

    "guitab \"New HUD#2\"\n"
    "guitext \"Spectator size:\" 0\n"
    "guislider newhud_spectatorsize\n"
    "guitext \"Spectator offset (X/Y):\" 0\n"
    "guislider newhud_spectatorpos_x\n"
    "guislider newhud_spectatorpos_y\n"

    "guitext \"Item size:\" 0\n"
    "guislider newhud_itemssize\n"
    "guitext \"Item offset (X/Y):\" 0\n"
    "guicheckbox \"Use reverse X offset\" newhud_itemspos_reverse_x\n"
    "guislider newhud_itemspos_x\n"
    "guislider newhud_itemspos_y\n"

    "guitext \"Chat Y offset:\" 0\n"
    "guislider newhud_miniconoffset\n"
    "guitext \"Chat lines:\" 0\n"
    "guislider newhud_miniconsize\n"
    "guitext \"Chat width:\" 0\n"
    "guislider newhud_miniconwidth\n"

"] \"Settings\"\n";

const char *game_scripts[] = { extended_settings_gui, hud_old, 0 };


#endif
